import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../styles/globals.css";
import "../../../styles/common.scss";
import { StoryblokProvider } from "../../../components/StoryblokProvider";
import Navigation from "../../../components/Navigation";
import Footer from "../../../components/footerNavigation";
import Theme from "../../../components/Theme";
import { getSiteConfig } from "@/lib/getSiteConfig";
import SocialIcons from "@/components/SocialIcons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const siteConfig = await getSiteConfig(params.lang, "ricekrispies");

  return (
    <StoryblokProvider>
      <html lang="en" data-theme={siteConfig?.content?.site || "ricekrispies"}>
      <head>
          <link rel="icon" href={siteConfig?.content?.favicon?.filename || "favicon.ico"} />
        </head>
        <body className={`${inter.className} bg-blue-50`}>
          <Theme theme={siteConfig?.content?.site} />
          <Navigation navigation={siteConfig?.content?.navigation[0]} />
          <main className="container mx-auto">{children}</main>
          <Footer footerBlocks={siteConfig?.content?.footerBlocks} />
          <SocialIcons
            socialIcons={siteConfig?.content?.socialIcons}
            copyRightSymbol={siteConfig?.content?.copyRightSymbol}
            copyRightDescription={siteConfig?.content?.copyRightDescription}
          />
        </body>
      </html>
    </StoryblokProvider>
  );
}
