import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/Banner.scss";
import "./styles/ProductDetails.scss";
import { StoryblokProvider } from "./components/StoryblokProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${inter.className} bg-blue-50`}>
          {children}
        </body>
      </html>
      </StoryblokProvider>
  );
}